stages:
  - test
  - build
  - deploy

# YAML anchor for reusable configuration
.poetry_setup: &poetry_setup
  image: python:3.12
  cache:
    key: "${CI_COMMIT_REF_SLUG}-poetry"
    paths:
      - .cache/pip
      - .cache/pypoetry
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false
    - poetry install

unit_test:
  stage: test
  <<: *poetry_setup  # Include reusable config
  script:
    - poetry run pytest
  
build_whl:
  stage: build
  needs:
    - unit_test
  <<: *poetry_setup  
  script:
    - poetry build --format wheel
  artifacts:
    paths:
      - dist/*.whl
    expire_in: 3 days

build_image:
  stage: deploy
  needs:
    - build_whl
  dependencies:
    - build_whl
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination ${CI_REGISTRY_IMAGE}:$CI_COMMIT_SHORT_SHA